version: '3'
services:
  web:
    container_name: bpc-python
    image: bpc0081/docker-python-test:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:4545"
    networks:
      - webnet
networks:
  webnet:

