version: 2
jobs:
  checkout_image:
    docker:
      - image: bpc0081/docker-python-test:v1
    steps:
      - checkout
      - run: mkdir ~/tmp
      - run: mkdir ~/tmp/test-results
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - test-results

  set_up_virtual_enviroment:
    docker:
      - image: bpc0081/docker-python-test:v1
    steps:
      - checkout
      - run:
          name: Setting up virtual enviroment 
          command: |
            pip install virtualenv
            virtualenv venv
      - persist_to_workspace:
          root: .
          paths:
            - venv

  # requirements.txt are actually pre-installed globally, 
  # here I am testing with virutal enviroment using circle ci's workspace
  # I can force a fail test by 1) Not installing the requirements in virtual, 
  # and 2.) Run tests in virtual i.e. missing flask library

  install_required_libraries:
    docker:
      - image: bpc0081/docker-python-test:v1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enter virtual enviroment
          command: |
            source venv/bin/activate
      - run:
          name: Install requirements.txt
          command: |
            pip install -r requirements.txt

  run_tests:
    docker:
      - image: bpc0081/docker-python-test:v1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enter virtual enviroment
          command: |
            source venv/bin/activate
      - run:
          name: Run Test Case 1
          command: |
            python test.py
      - run:
          name: Run Flask Test Case
          command: |
            python test_flask.py
      - store_test_results:
          path: ~/tmp/test-results

  deploy-to-docker-repository:
    docker:
      - image: bpc0081/docker-python-test:v1
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
            apt-get install curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run:
          name: Docker build image
          command: docker build -t bpc0081/docker-python-test:v1 .
      # deploy the image
      - run: 
          name: Docker push image
          command: docker push bpc0081/docker-python-test:v1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_image
      - set_up_virtual_enviroment:
          requires:
            - checkout_image
      - install_required_libraries:
          requires:
            - set_up_virtual_enviroment
      - run_tests:
          requires:
            - install_required_libraries
      - deploy-to-docker-repository:
          requires:
            - run_tests

